python:
  - "2.7"

install:
  - sudo apt-get install libev-dev
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install busted 1.9.0-1

script: "sudo luarocks make rockspecs/emitter-scm-1.rockspec && busted spec"

